---
build_deb:
  stage: build
  image: registry.ddbuild.io/ci/datadog-agent-buildimages/linux:$CI_IMAGE_LINUX
  tags: [arch:amd64]
  variables:
    DD_PKG_ARCH: x86_64
  artifacts:
    expire_in: 2 weeks
    paths:
      - $OMNIBUS_PACKAGE_DIR
  before_script:
    - source /root/.bashrc
  script:
    - bundle install
    - PACKAGE_VERSION=${PACKAGE_VERSION_OVERRIDE:-$RELEASE_VERSION_DEPLOY} bundle exec omnibus build ${PROJECT_NAME} --override=base_dir:${OMNIBUS_BASE_DIR}
    - mkdir -p $OMNIBUS_PACKAGE_DIR && cp $OMNIBUS_BASE_DIR/pkg/datadog-signing-keys*.deb{,.metadata.json} $OMNIBUS_PACKAGE_DIR
    - find ${OMNIBUS_PACKAGE_DIR} -iregex '.*\.\(deb\|rpm\)' | xargs dd-pkg lint || true
    - dd-pkg sign --key-id "${PIPELINE_KEY_ALIAS}" "${OMNIBUS_PACKAGE_DIR}"
